package com.pcms.technician.dto;

import java.time.LocalDate;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TechnicianRequest {

    @NotBlank(message = "Technician name is required")
    @Size(
            max = 100,
            message = "Name cannot exceed 100 characters"
    )
    private String fullName;

    @NotBlank(message = "Email is required")
    @Email(message = "Enter a valid email address")
    @Size(
            max = 150,
            message = "Email cannot exceed 150 characters"
    )
    private String email;

    @NotBlank(message = "Phone number is required")
    @Pattern(
            regexp = "^[0-9]{10}$",
            message = "Enter a valid 10-digit phone number"
    )
    private String phone;

    @NotBlank(message = "Address is required")
    @Size(
            max = 500,
            message = "Address cannot exceed 500 characters"
    )
    private String address;

    @NotBlank(message = "Specialization is required")
    @Size(
            max = 100,
            message = "Specialization cannot exceed 100 characters"
    )
    private String specialization;

    @NotNull(message = "Experience is required")
    @Min(
            value = 0,
            message = "Experience cannot be negative"
    )
    @Max(
            value = 50,
            message = "Experience cannot exceed 50 years"
    )
    private Integer experienceYears;

    @NotNull(message = "Date of birth is required")
    private LocalDate dateOfBirth;

    @NotBlank(message = "Gender is required")
    @Pattern(
            regexp = "^(Male|Female|Other)$",
            message = "Gender must be Male, Female or Other"
    )
    private String gender;

    /*
     * Base64 data URL generated by the React FileReader.
     * Example: data:image/jpeg;base64,/9j/4AAQ...
     */
    @Size(
            max = 3000000,
            message = "Profile photo is too large"
    )
    private String profilePhoto;

    /*
     * Legacy emergency phone field retained so older frontend
     * code continues to work.
     */
    @Pattern(
            regexp = "^[0-9]{10}$",
            message = "Enter a valid emergency contact number"
    )
    private String emergencyContact;

    @Size(
            max = 100,
            message = "Emergency contact name cannot exceed 100 characters"
    )
    private String emergencyContactName;

    @Pattern(
            regexp = "^[0-9]{10}$",
            message = "Enter a valid emergency contact number"
    )
    private String emergencyContactPhone;

    @Size(
            max = 50,
            message = "Relationship cannot exceed 50 characters"
    )
    private String emergencyContactRelationship;
}